API/urls.py
from django.urls import path
from API.views import ListCreateContacts, SearchContacts, UpdateContact, DeleteContact

urlpatterns = [
    path('list/', ListCreateContacts.as_view(), name='list-contact'),
    path('search/', SearchContacts.as_view(), name='search-contact'),
    path('create/', ListCreateContacts.as_view(), name='create-contact'),
    path('update/', UpdateContact.as_view(), name='update-contact'),
    path('delete/<int:pk>', DeleteContact.as_view(), name='delete-contact'),
]

PhoneList/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('home:home'), name='redirect-root'),
    path('api/', include(('API.urls', 'API'), namespace='api')),
    path('phone-list/', include(('home.urls', 'home'), namespace='home')),
]

home/urls.py
from django.urls import path
from django.views.generic import TemplateView

from home.views import CreateContactView, ListContactView, UpdateContactView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/home.html'), name='home'),
    path('create/', CreateContactView.as_view(), name='create-contact'),
    path('list/', ListContactView.as_view(), name='list-contact'),
    path('<int:pk>/update/', UpdateContactView.as_view(), name='update-contact'),
]

home/models.py
from django.db import models


class Contact(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    country_code = models.CharField(max_length=7)
    phone_number = models.CharField(unique=True)
    country = models.CharField(max_length=127, null=True, blank=True)
    city = models.CharField(max_length=127, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.first_name} - {self.last_name} - {self.country_code} {self.phone_number}'

    class Meta:
        unique_together = (('first_name', 'last_name'),)

home/forms.py
from django.forms import ModelForm
from home.models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        exclude = ('id', 'created_time')

API/views.py
from API.serializers import ContactSerializer, ListContactSerializer, Contact
from rest_framework.generics import ListAPIView, DestroyAPIView, UpdateAPIView, ListCreateAPIView


class SearchContacts(ListAPIView):
    queryset = Contact.objects.all()
    serializer_class = ListContactSerializer

    def get_queryset(self):
        first_name = self.request.query_params.get('first-name', '')
        # last_name = self.request.query_params.get('last-name', '')
        # city = self.request.query_params.get('city', '')
        # country = self.request.query_params.get('country', '')

        return Contact.objects.filter(first_name__icontains=first_name)
                                      # last_name__icontains=last_name,
                                      # country__icontains=country,
                                      # city__icontains=city)


class ListCreateContacts(ListCreateAPIView):
    queryset = Contact.objects.all()
    serializer_class = ListContactSerializer


class UpdateContact(UpdateAPIView):
    queryset = Contact.objects.all()
    serializer_class = ContactSerializer


class DeleteContact(DestroyAPIView):
    queryset = Contact.objects.all()
    serializer_class = ContactSerializer

home/views.py
from django.views.generic import FormView, ListView, UpdateView
from django.urls import reverse_lazy
from home.forms import ContactForm, Contact


class ListContactView(ListView):
    model = Contact
    context_object_name = 'contacts'
    template_name = 'home/list.html'
    ordering = '-created_time'


class CreateContactView(FormView):
    form_class = ContactForm
    template_name = 'home/create-update.html'
    success_url = reverse_lazy('home:list-contact')

    def form_valid(self, form):
        form.save()
        return super(CreateContactView, self).form_valid(form)


class UpdateContactView(UpdateView):
    model = Contact
    form_class = ContactForm
    template_name = 'home/create-update.html'
    success_url = reverse_lazy('home:list-contact')

    def form_valid(self, form):
        form.save()
        return super(UpdateContactView, self).form_valid(form)

home/templates/home/create-update.html
{% extends 'base.html' %}

{% block styles %}
    {% load crispy_forms_tags %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
{% endblock %}

{% block title %}Contacts List{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}

{% block title %}Contacts List{% endblock %}

{% block content %}
    <div class="red" style="background-color: #a5cce5; height: 100px; font-size: 20px; text-align: center"> ): چیزی به ذهنم نیومد بزارم</div>
    <div class="red" style="background-color: #65a6c2; height: 100px"></div>
    <div class="red" style="background-color: #6578c2; height: 100px"></div>
    <div class="red" style="background-color: #C26580; height: 100px"></div>
{% endblock %}

home/templates/home/list.html
{% extends 'base.html' %}

{% block styles %}
    {% load crispy_forms_tags %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
{% endblock %}

{% block title %}Contacts List{% endblock %}

{% block content %}
    <h1 id="title">List of Contacts</h1>

    <input id="search-input" autocomplete="off" type="text" aria-label="search-input" placeholder="Enter your contact's name...">

    <div id="card-container">
        {% for contact in contacts %}
            <div class="card" id="rem{{ contact.id }}">
              <div class="card-body">
                <h5 class="card-title">{{ contact.first_name }} {{ contact.last_name }}</h5>
                <p class="card-text">{{ contact.country }}, {{ contact.city }}, {{ contact.address }}</p>
                <p>{{ contact.country_code }} {{ contact.phone_number }}</p>
                <p>{{ contact.created_time }}</p>
                <button class="btn btn-danger" id="{{ contact.id }}">Remove</button>
                <a href="/phone-list/{{ contact.id }}/update/"><button class="btn btn-secondary">Edit</button></a>
              </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block script %}
    {% load static %}
    <script src="{% static 'home/delete.js' %}"></script>
    <script src="{% static 'home/fill.js' %}"></script>
    <script src="{% static 'home/modal.js' %}"></script>
{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}

{% block styles %}
    {% load crispy_forms_tags %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
{% endblock %}

{% block title %}Contacts List{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

templates/base.html
<html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
      {% block title %}<title>Phone-List</title>{% endblock %}
      {% load static %}
      <link rel="icon" href="{% static 'image/logo.png' %}" type="image/x-icon"/>
      <link rel="stylesheet" href="{% static 'styles.css' %}">
      <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
      {% block styles %}{% endblock %}
      <style>
          :root {

          }

          @font-face {
              font-family: "PoetsenOne";
              src: url("{% static 'font/PoetsenOne-Regular.ttf' %}");
          }

          @font-face {
              font-family: "MFF_italics";
              src: url("{% static 'font/MFF_italics.ttf' %}");
          }

          @font-face {
              font-family: "AnjomanMedium";
              src: url("{% static 'font/Anjoman-Medium.ttf' %}");
          }

          @font-face {
              font-family: "AnjomanMediumItalic";
              src: url("{% static 'font/Anjoman-MediumItalic.ttf' %}");
          }

          @font-face {
              font-family: "AnjomanLightItalic";
              src: url("{% static 'font/Anjoman-LightItalic.ttf' %}");
          }

          @font-face {
            font-family: "AnjomanCondensedHeavy";
              src: url("{% static 'font/Anjoman-CondensedHeavy.ttf' %}");
          }

          @font-face {
              font-family: "AnjomanCondensedHeavyItalic";
              src: url("{% static 'font/Anjoman-CondensedHeavyItalic.ttf' %}");
          }

          @font-face {
              font-family: "AnjomanItalic";
              src: url("{% static 'font/Anjoman-Italic.ttf' %}");
          }

          :root {
            --gr1: linear-gradient(to right, #7186B0, #C26580);
            --card-background: #36454f;
            --card-text: #8195ba;
          }
      </style>
    </head>

    <body>
      <header class="sticky-header">
          <nav class="parent-navbar">
            <a href="{% url 'home:home' %}" class="nav-logo">Contacts</a>
            <nav id="main-navbar">
              <a href="{% url 'home:list-contact' %}" class="nav-item">List</a>
              <a href="{% url 'home:create-contact' %}" class="nav-item">Create</a>
            </nav>
            <nav id="mobile-nav">
              <div id="clicking">
                <svg class="icon" fill="white" width="5rem" height="5rem" viewBox="0 0 512 512">
                  <path d="M32 96v64h448V96H32zm0 128v64h448v-64H32zm0 128v64h448v-64H32z"></path>
                </svg>
              </div>
            </nav>
          </nav>
          <div id="mobile-content" class="fixed-mobile-menu">
            <div class="a-container"><a href="{% url 'home:list-contact' %}" class="nav-item">List</a></div>
            <div class="a-container"><a href="{% url 'home:create-contact' %}" class="nav-item">Create</a></div>
          </div>
      </header>


      <main>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
      </main>

      <script>
        let icon = document.getElementById("clicking");
        icon.onclick = function (e) {
          e.stopPropagation()
          var x = document.getElementById("mobile-content");
          x.classList.toggle("show");

          if (x.classList.contains("show")) {
              x.style.top = "60px"
              x.style.zIndex = "-1"
          } else {
              x.style.top = "-300px"
          }
        }
        document.onclick = function() {
          var x = document.getElementById("mobile-content");
          if (x.classList.contains("show")) {
            x.classList.remove("show");
            x.style.top = "-300px"
          }
        }
      </script>

      {% block script %}{% endblock %}

    </body>

    <footer>
    <div class="icon-set">
      <a target="_blank" href="https://github.com/amirkhgraphic"><iconify-icon icon="mdi:github" style="color: white;" width="50px"></iconify-icon></a>
      <a target="_blank" href="https://t.me/Amirkh_MoD"><iconify-icon icon="icon-park-outline:telegram" style="color: white;" width="50"></iconify-icon></a>
      <a target="_blank" href="https://quera.org/profile/Amirkh1996"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 150 150" width="55px"><defs><style>.cls-3{fill:none;}.cls-4{fill:white;}</style></defs><path class="cls-3" d="M0,.2H150v150H0Z" transform="translate(0 -0.2)"/><path class="cls-4" d="M75.32,12.58A61.65,61.65,0,1,0,137,74.23,61.65,61.65,0,0,0,75.32,12.58Zm36.32,79a18.78,18.78,0,0,1-2.15,8.75L79.33,70.12l-8,8,37.16,37.15-4,4,0,0a30.26,30.26,0,0,0-21.4-8.86H57.92A18.91,18.91,0,0,1,39,91.54V56.73A18.91,18.91,0,0,1,57.92,37.81h34.8a18.92,18.92,0,0,1,18.92,18.92Z" transform="translate(0 -0.2)"/></svg></a>
      <a target="_blank" href=""><iconify-icon icon="mdi:linkedin" style="color: white;" width="50"></iconify-icon></a>
    </div>
    <div class="bottom-footer">
      <p class="footer-text">
        &copy; Copyright 2023 - Amirhossein Khalili, All rights reserved.
      </p>
      <div class="links">
        <a href="/static">Home</a>
        <a href="https://amirkhgraphic.github.io/Portfolio-Website/" target="_blank">About</a>
        <a href="https://amirkhgraphic.github.io/Portfolio-Website/" target="_blank">Contact</a>
        <a href="">Privacy</a>
      </div>
    </div>
    </footer>
    <div class="footer-line"></div>
</html>